/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReadoutsRouteImport } from './routes/readouts'
import { Route as MyNotesRouteImport } from './routes/my-notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoogleMeetRouteImport } from './routes/google-meet'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareTokenRouteImport } from './routes/share.$shareToken'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as InviteInviteTokenRouteImport } from './routes/invite.$inviteToken'
import { Route as FoldersFolderIdRouteImport } from './routes/folders.$folderId'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadoutsRoute = ReadoutsRouteImport.update({
  id: '/readouts',
  path: '/readouts',
  getParentRoute: () => rootRouteImport,
} as any)
const MyNotesRoute = MyNotesRouteImport.update({
  id: '/my-notes',
  path: '/my-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleMeetRoute = GoogleMeetRouteImport.update({
  id: '/google-meet',
  path: '/google-meet',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviteTokenRoute = InviteInviteTokenRouteImport.update({
  id: '/invite/$inviteToken',
  path: '/invite/$inviteToken',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/google-meet': typeof GoogleMeetRoute
  '/login': typeof LoginRoute
  '/my-notes': typeof MyNotesRoute
  '/readouts': typeof ReadoutsRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/vocabulary': typeof VocabularyRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/invite/$inviteToken': typeof InviteInviteTokenRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/google-meet': typeof GoogleMeetRoute
  '/login': typeof LoginRoute
  '/my-notes': typeof MyNotesRoute
  '/readouts': typeof ReadoutsRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/vocabulary': typeof VocabularyRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/invite/$inviteToken': typeof InviteInviteTokenRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/google-meet': typeof GoogleMeetRoute
  '/login': typeof LoginRoute
  '/my-notes': typeof MyNotesRoute
  '/readouts': typeof ReadoutsRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/vocabulary': typeof VocabularyRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/invite/$inviteToken': typeof InviteInviteTokenRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/chat'
    | '/google-meet'
    | '/login'
    | '/my-notes'
    | '/readouts'
    | '/settings'
    | '/shared'
    | '/tasks'
    | '/teams'
    | '/vocabulary'
    | '/folders/$folderId'
    | '/invite/$inviteToken'
    | '/notes/$noteId'
    | '/share/$shareToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/chat'
    | '/google-meet'
    | '/login'
    | '/my-notes'
    | '/readouts'
    | '/settings'
    | '/shared'
    | '/tasks'
    | '/teams'
    | '/vocabulary'
    | '/folders/$folderId'
    | '/invite/$inviteToken'
    | '/notes/$noteId'
    | '/share/$shareToken'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/chat'
    | '/google-meet'
    | '/login'
    | '/my-notes'
    | '/readouts'
    | '/settings'
    | '/shared'
    | '/tasks'
    | '/teams'
    | '/vocabulary'
    | '/folders/$folderId'
    | '/invite/$inviteToken'
    | '/notes/$noteId'
    | '/share/$shareToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  GoogleMeetRoute: typeof GoogleMeetRoute
  LoginRoute: typeof LoginRoute
  MyNotesRoute: typeof MyNotesRoute
  ReadoutsRoute: typeof ReadoutsRoute
  SettingsRoute: typeof SettingsRoute
  SharedRoute: typeof SharedRoute
  TasksRoute: typeof TasksRoute
  TeamsRoute: typeof TeamsRoute
  VocabularyRoute: typeof VocabularyRoute
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  InviteInviteTokenRoute: typeof InviteInviteTokenRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readouts': {
      id: '/readouts'
      path: '/readouts'
      fullPath: '/readouts'
      preLoaderRoute: typeof ReadoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-notes': {
      id: '/my-notes'
      path: '/my-notes'
      fullPath: '/my-notes'
      preLoaderRoute: typeof MyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-meet': {
      id: '/google-meet'
      path: '/google-meet'
      fullPath: '/google-meet'
      preLoaderRoute: typeof GoogleMeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviteToken': {
      id: '/invite/$inviteToken'
      path: '/invite/$inviteToken'
      fullPath: '/invite/$inviteToken'
      preLoaderRoute: typeof InviteInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  GoogleMeetRoute: GoogleMeetRoute,
  LoginRoute: LoginRoute,
  MyNotesRoute: MyNotesRoute,
  ReadoutsRoute: ReadoutsRoute,
  SettingsRoute: SettingsRoute,
  SharedRoute: SharedRoute,
  TasksRoute: TasksRoute,
  TeamsRoute: TeamsRoute,
  VocabularyRoute: VocabularyRoute,
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  InviteInviteTokenRoute: InviteInviteTokenRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
